export const GET_PIZZA_LIST = "GET_PIZZA_LIST";
export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const CHANGE_COUNT_PRODUCT = "CHANGE_COUNT_PRODUCT";
